- refactored project according to SOLID principles;
Marharitavol/8BallApp pull request #4
Opened 2021-11-07 20:54 UTC by Marharitavol

- removed singletones.

2021-11-08 16:29 UTC, ios-school-yalantis commented on 8BallApp/Controllers/ViewController.swift
> +    }
`ViewController` не должен сам создавать себе зависимости

2021-11-09 20:46 UTC, Marharitavol commented on 8BallApp/Controllers/ViewController.swift
> +    }
done

2021-11-09 20:54 UTC, ios-school-yalantis requested changes

2021-11-09 20:54 UTC, ios-school-yalantis commented on 8BallApp/Application/AppDelegate.swift
> +let repository = Repository()
нет, мы должны уйти от глобальных сервисов, они должны быть переданы нужным классам в момент создания, в случае с viewController в открытых переменных

2021-11-09 22:46 UTC, Marharitavol commented on 8BallApp/Application/AppDelegate.swift
> +let repository = Repository()
Я переписала первый экран кодом, поэтому смогла передать репозиторий в инициализацию ViewController'a. Но в данный момент, есть проблемы с UI, которые я исправлю в следующих коммитах.

2021-11-10 17:41 UTC, ios-school-yalantis approved these changes
есть незначительные комментарии, после их исправления можно мержить

2021-11-10 17:41 UTC, ios-school-yalantis commented on 8BallApp/Application/SceneDelegate.swift
> +            let navigationController = UINavigationController.init(rootViewController: ViewController(repository: repository))
можно удалить .init

2021-11-10 17:41 UTC, ios-school-yalantis commented on 8BallApp/Controllers/ViewController.swift
> +        }
форматирование поехало

2021-11-10 17:41 UTC, ios-school-yalantis commented on 8BallApp/Data/Repository.swift
> +    func fetchData(completion: @escaping (_ answer: String?)->())
лучше будет `func fetchData(completion: @escaping (_ answer: String?) -> Void)`

2021-11-10 18:58 UTC, merged