Feature/homework3
Marharitavol/8BallApp pull request #5
Opened 2021-11-11 22:18 UTC by Marharitavol

2021-11-12 12:29 UTC, seropusha requested changes
Стоит добавить папку `Resources`. и перенести в нее все ресурсы (Localizable.strings, Assets), так же переместить в нее папку Swiftgen с генерируемыми файлами помесям пути к ним в скрипте.

2021-11-12 12:29 UTC, seropusha commented on Podfile
> +  pod 'SwiftLint'
Лучше указывать версию линта

может быть проблема когда на CI и локально будут версии отличаться и будут не соответствия в работе. Будешь тратить время на поиски проблемы.

2021-11-12 12:29 UTC, seropusha commented on 8BallApp/Service/NetworkClient.swift
> +        guard let url = URL(string: L10n.apiUrl) else { return }
Не стоит добавлять url в локализированы строки. Это больше относится к бизнес логике, а в локализированы строки добавляем только то что будем отображать на экране.

2021-11-12 12:29 UTC, seropusha commented on 8BallApp/Service/UserDefaultsManager.swift
> +            let chosenAnswers = ["from API", "Just do it!", "Change your mind"]
все строки перенести в Localizable.strings

2021-11-12 20:12 UTC, Marharitavol commented on 8BallApp/Service/UserDefaultsManager.swift
> +            let chosenAnswers = ["from API", "Just do it!", "Change your mind"]
Исправила все замечания.

2021-11-15 16:17 UTC, seropusha commented on 8BallApp/Controllers/SettingsViewController.swift
> +        tableView.register(UITableViewCell.self, forCellReuseIdentifier: L10n.identifier)
Identifier не обязательно в строки добавлять так как это больше к метаданных относится

Обычно задают вот так `String(describing: YourType.self)` Identifier  будет такой же как и название класса.

2021-11-15 16:20 UTC, seropusha approved these changes
общем все хорошо
можно мерджить

2021-11-16 21:26 UTC, merged